name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -project CICDTest.xcodeproj -scheme "CICDTest" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max"
    - name: Run tests
      run: xcodebuild test -project CICDTest.xcodeproj -scheme "CICDTestTests" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max"

  build-frameworks:

    needs: build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Xcframeworks Script permissions
        run: chmod +x dummy_bash.sh
      - name: Create xcframeworks
        run: ./dummy_bash.sh

  build-veracode:
  
    needs: build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Veracode Script permissions
        run: chmod +x veracode.sh
      - name: Build Veracode Package
        run: ./veracode.sh      