name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcode-select -s /Applications/Xcode.app && set -o pipefail && /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild clean -scheme CICDTest build-for-testing -allowProvisioningUpdates
      #swift build -v
    - name: Run tests
      run: set -o pipefail && /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun $(find . -type f -name "*.xctestrun") -destination "platform=iOS Simulator,name=$DEVICE" -enableCodeCoverage YES
      #swift test -v