name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd ../.. && xcodebuild -project CICDTest.xcodeproj -scheme "CICDTest" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max"
    - name: Run tests
      run: cd ../.. && xcodebuild test -project CICDTest.xcodeproj -scheme "CICDTestTests" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max"
